const data = [
  {
    id: 1,
    type: "cabins",
    location: "Sasaima, Colombia",
    rating: 4.96,
    guests: 2,
    bedrooms: 2,
    beds: 1,
    baths: 1,
    title: "The most spectacular treehouse in Colombia",
    subtitle: "Treehouse hosted by Houses In The Sky",
    price: 311850,
    reviews: 245,
    description: `Two hours from Bogotá via Bogotá - Sasaima, experience the unique experience of staying in a tree eight meters above sea level.
      Wake up to the bird whistle and lie down to the sound of the creek below.
      Enjoy a five-star suite with all the comforts in the branches of trees.
      The cabin will be just for you and features hot water, mini fridge and the most spectacular view!
      Delicious breakfast included!`,
    wifi: true,
    tv: false,
    washer: false,
    ac: false,
    heating: true,
    breakfast: true,
    freeParking: true,
    refrigerator: true,
    freezer: true,
    dishwasher: true,
    stove: true,
    oven: true,
    coffeeMaker: true,
    url: "https://www.airbnb.com/rooms/46070163?adults=1&category_tag=Tag%3A5348&children=0&infants=0&search_mode=flex_destinations_search&check_in=2023-01-30&check_out=2023-02-04&federated_search_id=d77b591d-b097-464d-ac78-71ac7d70bf71&source_impression_id=p3_1673730594_CodZnX0IhQCHf9YA",
  },
  {
    id: 2,
    type: "cabins",
    location: "Medellín, Colombia",
    rating: 4.94,
    guests: 2,
    bedrooms: 1,
    beds: 1,
    baths: 1,
    title: "Chalet Boutique Saltamontes Santa Elena",
    subtitle: "Entire cabin hosted by Natalia",
    price: 220000,
    reviews: 211,
    description: `On the mountain and under the stars you can stay in a cozy and authentic space surrounded by forest and flowers where you will reconnect with life on the countryside.`,
    wifi: true,
    tv: false,
    washer: true,
    ac: false,
    heating: true,
    breakfast: true,
    freeParking: true,
    refrigerator: true,
    freezer: true,
    dishwasher: true,
    stove: true,
    oven: true,
    coffeeMaker: true,
    url: "https://www.airbnb.com/rooms/44491433?adults=1&category_tag=Tag%3A5348&children=0&infants=0&search_mode=flex_destinations_search&check_in=2023-02-05&check_out=2023-02-10&federated_search_id=d77b591d-b097-464d-ac78-71ac7d70bf71&source_impression_id=p3_1673732387_gZIKGTgE1G%2FYb3qw",
  },
  {
    id: 3,
    type: "cabins",
    location: "Cajicá, Colombia",
    rating: 4.95,
    guests: 2,
    bedrooms: 1,
    beds: 1,
    baths: 1,
    title: "Casa Anís",
    subtitle: "Entire chalet hosted by Doris",
    price: 151360,
    reviews: 176,
    description: `Private cottage in a country setting with easy access to public transport. It has a large green area,parking and special spaces for roasting and bonfire. Perfect to get out of the routine and visit the tourist sites near Cajicá, such as: Zipaquira Salt Cathedral, Nemocón Salt Mine, Neusa Dam, Tabio Thermal Baths, La Montaña de Juaica, Jaime Duque Park, Señor de la piedra in Sopó, Cogua and its gastronomy, sport fishing and paragliding in Sopó.`,
    wifi: true,
    tv: false,
    washer: false,
    ac: false,
    heating: false,
    breakfast: true,
    freeParking: true,
    refrigerator: true,
    freezer: true,
    dishwasher: true,
    stove: true,
    oven: true,
    coffeeMaker: true,
    url: "https://www.airbnb.com/rooms/38412890?adults=1&category_tag=Tag%3A5348&children=0&infants=0&search_mode=flex_destinations_search&check_in=2023-01-23&check_out=2023-01-28&federated_search_id=d77b591d-b097-464d-ac78-71ac7d70bf71&source_impression_id=p3_1673737058_5V%2F5QkG31bYfXrRa",
  },
  {
    id: 4,
    type: "cabins",
    location: "Sopó, Colombia",
    rating: 4.99,
    guests: 2,
    bedrooms: 1,
    beds: 1,
    baths: 1,
    title: "Finca La Diva Bed & Breakfast",
    subtitle: "Private room in farm stay hosted by Juan David",
    price: 230000,
    reviews: 270,
    description: `Beautiful mountain landscapes, birds observation, natural mountain forest. English and German speakers.`,
    wifi: true,
    tv: true,
    washer: true,
    ac: false,
    heating: true,
    breakfast: true,
    freeParking: true,
    refrigerator: true,
    freezer: true,
    dishwasher: true,
    stove: true,
    oven: true,
    coffeeMaker: true,
    url: "https://www.airbnb.com/rooms/17244932/amenities?adults=1&category_tag=Tag%3A5348&children=0&infants=0&search_mode=flex_destinations_search&check_in=2023-02-06&check_out=2023-02-11&federated_search_id=d77b591d-b097-464d-ac78-71ac7d70bf71&source_impression_id=p3_1673737061_5DIaInGcKZbIf%2BXO",
  },
  {
    id: 5,
    type: "cabins",
    location: "Medellín, Colombia",
    rating: 4.89,
    guests: 2,
    bedrooms: 1,
    beds: 1,
    baths: 1,
    title: "Cozy Cabin in Santa Elena - Villa Bavaria",
    subtitle: "Entire cabin hosted by Daniel",
    price: 95000,
    reviews: 66,
    description: `Villa Baviera is the perfect place to reunite with your inner self and nature. Been surrounded by trees, hearing at the birds singing while enjoying a cup of hot coffee it's the perfect beginning for a productive and happy day. 
Santa Elena is famous for its forest hikes and bicycle roads, if you love one of those two then stop looking and book now.`,
    wifi: true,
    tv: true,
    washer: true,
    ac: false,
    heating: false,
    breakfast: true,
    freeParking: true,
    refrigerator: true,
    freezer: true,
    dishwasher: true,
    stove: true,
    oven: true,
    coffeeMaker: true,
    url: "https://www.airbnb.com/rooms/44352933?adults=1&category_tag=Tag%3A5348&children=0&infants=0&search_mode=flex_destinations_search&check_in=2023-01-23&check_out=2023-01-28&federated_search_id=897b85c2-a7dd-402c-b640-f350dbd54bb2&source_impression_id=p3_1673990263_j47RVtp73PlO%2BEvt",
  },
  {
    id: 6,
    type: "cabins",
    location: "Guatape, Colombia",
    rating: 4.8,
    guests: 7,
    bedrooms: 3,
    beds: 5,
    baths: 2,
    title: "Guatape cottage house overlooking the lake and the Peñol",
    subtitle: "Entire home hosted by Raul",
    price: 550800,
    reviews: 101,
    description: `Municipality of Peñol -Guatapé Entire accommodation for 7 people with hot water, located 5 min from the pier and opposite the peñol stone where you can enjoy beautiful sunsets that make this place a quiet, family and unforgettable space, friendly with animals with parking for three vehicles.
Come and enjoy yourself and give us the pleasure of hosting.
Nightly prices`,
    wifi: true,
    tv: false,
    washer: false,
    ac: false,
    heating: false,
    breakfast: true,
    freeParking: true,
    refrigerator: true,
    freezer: true,
    dishwasher: true,
    stove: true,
    oven: true,
    coffeeMaker: true,
    url: "https://www.airbnb.com/rooms/46768383?adults=1&category_tag=Tag%3A5348&children=0&infants=0&search_mode=flex_destinations_search&check_in=2023-01-14&check_out=2023-01-19&federated_search_id=897b85c2-a7dd-402c-b640-f350dbd54bb2&source_impression_id=p3_1673990264_8SGr%2F5VMJzDIJa7z",
  },
  {
    id: 7,
    type: "cabins",
    location: "Tabio, Colombia",
    rating: 4.86,
    guests: 2,
    bedrooms: 1,
    beds: 1,
    baths: 1,
    title: "Tuwa Shima Mountainside Cabin",
    subtitle: "Entire cabin hosted by Lorna",
    price: 176918,
    reviews: 87,
    description: `A beautiful cabin in the mountains of Tabio. The perfect escape to relax and finish that book, surrounded by nature. 5 minutes from the town by car or bus, and 1 hour by car from Bogotá. The cabin has wonderful views of La Peña de Juaica, a cozy living room with a sofa, a double bedroom with a balcony, and a spectacular bathroom with a glass ceiling, so you can take a shower surrounded by trees! It also has its own garden with a fire pit and solar lights.
We speak Spanish and English.`,
    wifi: true,
    tv: false,
    washer: false,
    ac: false,
    heating: false,
    breakfast: true,
    freeParking: true,
    refrigerator: true,
    freezer: true,
    dishwasher: true,
    stove: true,
    oven: true,
    coffeeMaker: true,
    url: "https://www.airbnb.com/rooms/39674034?adults=1&category_tag=Tag%3A5348&children=0&infants=0&search_mode=flex_destinations_search&check_in=2023-01-15&check_out=2023-01-20&federated_search_id=897b85c2-a7dd-402c-b640-f350dbd54bb2&source_impression_id=p3_1673990264_R2JCLCn%2FbHR9ZpwM",
  },
  {
    id: 8,
    type: "cabins",
    location: "Salento, Colombia",
    rating: 4.9,
    guests: 4,
    bedrooms: 2,
    beds: 2,
    baths: 1,
    title: "Glamping Salento, lujo& confort",
    subtitle: "Hut hosted by Natalia",
    price: 555000,
    reviews: 21,
    description: `Glamping Salento is made of 85% recycled plastic ( that means six tons of plastic did not go to landfills or water sources and that six tons of wood was not cut down!). We are located in the Boquia-Salento area, 30 minutes from Armenia and 10 from the town (Salento). Here you can connect with nature, spend a quiet night with your partner, friends or family, and the best of all is that it is very close to the city!`,
    wifi: true,
    tv: false,
    washer: false,
    ac: false,
    heating: false,
    breakfast: true,
    freeParking: true,
    refrigerator: true,
    freezer: true,
    dishwasher: true,
    stove: true,
    oven: true,
    coffeeMaker: true,
    url: "https://www.airbnb.com/rooms/50700517?adults=1&category_tag=Tag%3A5348&children=0&infants=0&search_mode=flex_destinations_search&check_in=2023-01-29&check_out=2023-02-03&federated_search_id=897b85c2-a7dd-402c-b640-f350dbd54bb2&source_impression_id=p3_1673990265_QSphsCz3rYvp1llc",
  },
  {
    id: 9,
    type: "beachfront",
    location: "San Blas Islands, Panama",
    rating: 0,
    guests: 2,
    bedrooms: 1,
    beds: 1,
    baths: 1,
    title: "Enjoy San Blas - Deluxe Private Bath - Diablo Island",
    subtitle: "Entire cabin hosted by Adriham",
    price: 930384,
    reviews: 0,
    description: `Luxury cabins with private bathroom, ocean views and all meals included! Enjoy your vacation in one of the most heavenly destinations in the Caribbean.`,
    wifi: false,
    tv: false,
    washer: false,
    ac: false,
    heating: false,
    breakfast: true,
    freeParking: true,
    refrigerator: true,
    freezer: true,
    dishwasher: true,
    stove: true,
    oven: true,
    coffeeMaker: true,
    url: "https://www.airbnb.com/rooms/53096363?adults=1&category_tag=Tag%3A789&children=0&infants=0&search_mode=flex_destinations_search&check_in=2023-01-16&check_out=2023-01-21&federated_search_id=c1ef2203-f618-48be-923c-0ccde151fdd6&source_impression_id=p3_1674005911_dTFDMKPQx6%2FuWHQo",
  },
  {
    id: 10,
    type: "beachfront",
    location: "Viento Frío, Panama",
    rating: 0,
    guests: 10,
    bedrooms: 3,
    beds: 6,
    baths: 3.5,
    title: "Casa Canalú",
    subtitle: "Entire home hosted by Federico",
    price: 1691608,
    reviews: 2,
    description: `Enjoy the sounds of the sea when you stay in this unique place. The sea in front of the property is like a natural pool.
The property is located six meters from the sea so you can always enjoy the sea breeze from a hammock. Those who like to cook will have a fully equipped kitchen. The 3 comfortable rooms, which are separated from each other, have Air Conditioning, fans and WiFi. Parking for Multiple Cars`,
    wifi: true,
    tv: true,
    washer: true,
    ac: true,
    heating: false,
    breakfast: true,
    freeParking: true,
    refrigerator: true,
    freezer: true,
    dishwasher: true,
    stove: true,
    oven: true,
    coffeeMaker: true,
    url: "https://www.airbnb.com/rooms/52613523?adults=1&category_tag=Tag%3A789&children=0&infants=0&search_mode=flex_destinations_search&check_in=2023-01-21&check_out=2023-01-26&federated_search_id=c1ef2203-f618-48be-923c-0ccde151fdd6&source_impression_id=p3_1674006703_1tpPEKmedkwB4%2Bj%2B",
  },
  {
    id: 11,
    type: "beachfront",
    location: "Tintipán Island, Colombia",
    rating: 0,
    guests: 16,
    bedrooms: 6,
    beds: 18,
    baths: 7,
    title: "Car009 - Magnificent eco-friendly house on Tintipan Island",
    subtitle: "Entire villa hosted by Latin Exclusive",
    price: 10833807,
    reviews: 0,
    description: `This unique and stunning beach villa has the privilege of being located in Tintipan Island a magical and exclusive spot right in the middle of a protected natural region from Colombia's Caribbean islands.`,
    wifi: true,
    tv: true,
    washer: true,
    ac: true,
    heating: false,
    breakfast: true,
    freeParking: true,
    refrigerator: true,
    freezer: true,
    dishwasher: true,
    stove: true,
    oven: true,
    coffeeMaker: true,
    url: "https://www.airbnb.com/rooms/46775204?adults=1&category_tag=Tag%3A789&children=0&infants=0&search_mode=flex_destinations_search&check_in=2023-01-29&check_out=2023-02-03&federated_search_id=cfdd5ad0-d21d-4983-8780-d9cd5dca4343&source_impression_id=p3_1674007518_%2FHm4Z943Nd6WF4H2",
  },
  {
    id: 12,
    type: "beachfront",
    location: "Coveñas, Colombia",
    rating: 4.97,
    guests: 8,
    bedrooms: 2,
    beds: 7,
    baths: 2,
    title: "Magical oceanfront 2 Bedroom Apartment",
    subtitle: "Entire rental unit hosted by Oliver",
    price: 415333,
    reviews: 155,
    description: `Enjoy a beautiful apartment that blends the comfort of waterfront rest with a perfect setting to relax and forget all worries. This apartment is located on the first cove, the most exclusive site in Coveñas. Waking up in the morning and having breakfast in front of the sea on the balcony or on the beach kiosks is a dream you can realize every day. The condo has a private swimming pool, children's pool, terraces and volleyball court.`,
    wifi: true,
    tv: true,
    washer: true,
    ac: true,
    heating: false,
    breakfast: true,
    freeParking: true,
    refrigerator: true,
    freezer: true,
    dishwasher: true,
    stove: true,
    oven: true,
    coffeeMaker: true,
    url: "https://www.airbnb.com/rooms/38350791?adults=1&category_tag=Tag%3A789&children=0&infants=0&search_mode=flex_destinations_search&check_in=2023-02-03&check_out=2023-02-09&federated_search_id=cfdd5ad0-d21d-4983-8780-d9cd5dca4343&source_impression_id=p3_1674007518_cmmJbSyEM0fs1%2Buo",
  },
  {
    id: 13,
    type: "beachfront",
    location: "Coveñas, Colombia",
    rating: 4.96,
    guests: 8,
    bedrooms: 3,
    beds: 7,
    baths: 2,
    title: "Magic 3 Bedroom Seafront Apartment",
    subtitle: "Entire rental unit hosted by Oliver",
    price: 390400,
    reviews: 79,
    description: `Enjoy a beautiful apartment that blends the comfort of waterfront rest with a perfect setting to relax and forget all worries. This apartment is located on the first cove, the most exclusive site in Coveñas. Waking up in the morning and having breakfast in front of the sea on the balcony or at the poolside tables is a dream you can realize every day. Enjoy spectacular ocean views from the magical balcony.`,
    wifi: true,
    tv: true,
    washer: true,
    ac: true,
    heating: false,
    breakfast: true,
    freeParking: true,
    refrigerator: true,
    freezer: true,
    dishwasher: true,
    stove: true,
    oven: true,
    coffeeMaker: true,
    url: "https://www.airbnb.com/rooms/48679354?adults=1&category_tag=Tag%3A789&children=0&infants=0&search_mode=flex_destinations_search&check_in=2023-01-27&check_out=2023-02-01&federated_search_id=cfdd5ad0-d21d-4983-8780-d9cd5dca4343&source_impression_id=p3_1674007519_Y1zn%2B9PMgIfP1LkT",
  },
  {
    id: 0,
    type: "",
    location: "",
    rating: 0,
    guests: 0,
    bedrooms: 0,
    beds: 0,
    baths: 0,
    title: "",
    subtitle: "",
    price: 0,
    reviews: 0,
    description: ``,
    wifi: true,
    tv: true,
    washer: true,
    ac: true,
    heating: true,
    breakfast: true,
    freeParking: true,
    refrigerator: true,
    freezer: true,
    dishwasher: true,
    stove: true,
    oven: true,
    coffeeMaker: true,
    url: "",
  },
];

export default data;
