const data = [
  {
    id: 1,
    type: "cabins",
    location: "Sasaima, Colombia",
    rating: 4.96,
    guests: 2,
    bedrooms: 2,
    beds: 1,
    baths: 1,
    title: "The most spectacular treehouse in Colombia",
    subtitle: "Treehouse hosted by Houses In The Sky",
    price: 311850,
    reviews: 245,
    description: `Two hours from Bogotá via Bogotá - Sasaima, experience the unique experience of staying in a tree eight meters above sea level.
      Wake up to the bird whistle and lie down to the sound of the creek below.
      Enjoy a five-star suite with all the comforts in the branches of trees.
      The cabin will be just for you and features hot water, mini fridge and the most spectacular view!
      Delicious breakfast included!`,
    wifi: true,
    tv: false,
    washer: false,
    ac: false,
    heating: true,
    breakfast: true,
    freeParking: true,
    refrigerator: true,
    freezer: true,
    dishwasher: true,
    stove: true,
    oven: true,
    coffeeMaker: true,
    url: "https://www.airbnb.com/rooms/46070163?adults=1&category_tag=Tag%3A5348&children=0&infants=0&search_mode=flex_destinations_search&check_in=2023-01-30&check_out=2023-02-04&federated_search_id=d77b591d-b097-464d-ac78-71ac7d70bf71&source_impression_id=p3_1673730594_CodZnX0IhQCHf9YA",
  },
  {
    id: 2,
    type: "cabins",
    location: "Medellín, Colombia",
    rating: 4.94,
    guests: 2,
    bedrooms: 1,
    beds: 1,
    baths: 1,
    title: "Chalet Boutique Saltamontes Santa Elena",
    subtitle: "Entire cabin hosted by Natalia",
    price: 220000,
    reviews: 211,
    description: `On the mountain and under the stars you can stay in a cozy and authentic space surrounded by forest and flowers where you will reconnect with life on the countryside.`,
    wifi: true,
    tv: false,
    washer: true,
    ac: false,
    heating: true,
    breakfast: true,
    freeParking: true,
    refrigerator: true,
    freezer: true,
    dishwasher: true,
    stove: true,
    oven: true,
    coffeeMaker: true,
    url: "https://www.airbnb.com/rooms/44491433?adults=1&category_tag=Tag%3A5348&children=0&infants=0&search_mode=flex_destinations_search&check_in=2023-02-05&check_out=2023-02-10&federated_search_id=d77b591d-b097-464d-ac78-71ac7d70bf71&source_impression_id=p3_1673732387_gZIKGTgE1G%2FYb3qw",
  },
  {
    id: 3,
    type: "cabins",
    location: "Cajicá, Colombia",
    rating: 4.95,
    guests: 2,
    bedrooms: 1,
    beds: 1,
    baths: 1,
    title: "Casa Anís",
    subtitle: "Entire chalet hosted by Doris",
    price: 151360,
    reviews: 176,
    description: `Private cottage in a country setting with easy access to public transport. It has a large green area,parking and special spaces for roasting and bonfire. Perfect to get out of the routine and visit the tourist sites near Cajicá, such as: Zipaquira Salt Cathedral, Nemocón Salt Mine, Neusa Dam, Tabio Thermal Baths, La Montaña de Juaica, Jaime Duque Park, Señor de la piedra in Sopó, Cogua and its gastronomy, sport fishing and paragliding in Sopó.`,
    wifi: true,
    tv: false,
    washer: false,
    ac: false,
    heating: false,
    breakfast: true,
    freeParking: true,
    refrigerator: true,
    freezer: true,
    dishwasher: true,
    stove: true,
    oven: true,
    coffeeMaker: true,
    url: "https://www.airbnb.com/rooms/38412890?adults=1&category_tag=Tag%3A5348&children=0&infants=0&search_mode=flex_destinations_search&check_in=2023-01-23&check_out=2023-01-28&federated_search_id=d77b591d-b097-464d-ac78-71ac7d70bf71&source_impression_id=p3_1673737058_5V%2F5QkG31bYfXrRa",
  },
  {
    id: 4,
    type: "cabins",
    location: "Sopó, Colombia",
    rating: 4.99,
    guests: 2,
    bedrooms: 1,
    beds: 1,
    baths: 1,
    title: "Finca La Diva Bed & Breakfast",
    subtitle: "Private room in farm stay hosted by Juan David",
    price: 230000,
    reviews: 270,
    description: `Beautiful mountain landscapes, birds observation, natural mountain forest. English and German speakers.`,
    wifi: true,
    tv: true,
    washer: true,
    ac: false,
    heating: true,
    breakfast: true,
    freeParking: true,
    refrigerator: true,
    freezer: true,
    dishwasher: true,
    stove: true,
    oven: true,
    coffeeMaker: true,
    url: "https://www.airbnb.com/rooms/17244932/amenities?adults=1&category_tag=Tag%3A5348&children=0&infants=0&search_mode=flex_destinations_search&check_in=2023-02-06&check_out=2023-02-11&federated_search_id=d77b591d-b097-464d-ac78-71ac7d70bf71&source_impression_id=p3_1673737061_5DIaInGcKZbIf%2BXO",
  },
  {
    id: 5,
    type: "cabins",
    location: "Medellín, Colombia",
    rating: 4.89,
    guests: 2,
    bedrooms: 1,
    beds: 1,
    baths: 1,
    title: "Cozy Cabin in Santa Elena - Villa Bavaria",
    subtitle: "Entire cabin hosted by Daniel",
    price: 95000,
    reviews: 66,
    description: `Villa Baviera is the perfect place to reunite with your inner self and nature. Been surrounded by trees, hearing at the birds singing while enjoying a cup of hot coffee it's the perfect beginning for a productive and happy day. 
Santa Elena is famous for its forest hikes and bicycle roads, if you love one of those two then stop looking and book now.`,
    wifi: true,
    tv: true,
    washer: true,
    ac: false,
    heating: false,
    breakfast: true,
    freeParking: true,
    refrigerator: true,
    freezer: true,
    dishwasher: true,
    stove: true,
    oven: true,
    coffeeMaker: true,
    url: "https://www.airbnb.com/rooms/44352933?adults=1&category_tag=Tag%3A5348&children=0&infants=0&search_mode=flex_destinations_search&check_in=2023-01-23&check_out=2023-01-28&federated_search_id=897b85c2-a7dd-402c-b640-f350dbd54bb2&source_impression_id=p3_1673990263_j47RVtp73PlO%2BEvt",
  },
  {
    id: 6,
    type: "cabins",
    location: "Guatape, Colombia",
    rating: 4.8,
    guests: 7,
    bedrooms: 3,
    beds: 5,
    baths: 2,
    title: "Guatape cottage house overlooking the lake and the Peñol",
    subtitle: "Entire home hosted by Raul",
    price: 550800,
    reviews: 101,
    description: `Municipality of Peñol -Guatapé Entire accommodation for 7 people with hot water, located 5 min from the pier and opposite the peñol stone where you can enjoy beautiful sunsets that make this place a quiet, family and unforgettable space, friendly with animals with parking for three vehicles.
Come and enjoy yourself and give us the pleasure of hosting.
Nightly prices`,
    wifi: true,
    tv: false,
    washer: false,
    ac: false,
    heating: false,
    breakfast: true,
    freeParking: true,
    refrigerator: true,
    freezer: true,
    dishwasher: true,
    stove: true,
    oven: true,
    coffeeMaker: true,
    url: "https://www.airbnb.com/rooms/46768383?adults=1&category_tag=Tag%3A5348&children=0&infants=0&search_mode=flex_destinations_search&check_in=2023-01-14&check_out=2023-01-19&federated_search_id=897b85c2-a7dd-402c-b640-f350dbd54bb2&source_impression_id=p3_1673990264_8SGr%2F5VMJzDIJa7z",
  },
  {
    id: 0,
    type: "",
    location: "",
    rating: 0,
    guests: 0,
    bedrooms: 0,
    beds: 0,
    baths: 0,
    title: "",
    subtitle: "",
    price: 0,
    reviews: 0,
    description: ``,
    wifi: true,
    tv: true,
    washer: true,
    ac: true,
    heating: true,
    breakfast: true,
    freeParking: true,
    refrigerator: true,
    freezer: true,
    dishwasher: true,
    stove: true,
    oven: true,
    coffeeMaker: true,
    url: "",
  },
  {
    id: 0,
    type: "",
    location: "",
    rating: 0,
    guests: 0,
    bedrooms: 0,
    beds: 0,
    baths: 0,
    title: "",
    subtitle: "",
    price: 0,
    reviews: 0,
    description: ``,
    wifi: true,
    tv: true,
    washer: true,
    ac: true,
    heating: true,
    breakfast: true,
    freeParking: true,
    refrigerator: true,
    freezer: true,
    dishwasher: true,
    stove: true,
    oven: true,
    coffeeMaker: true,
    url: "",
  },
  {
    id: 0,
    type: "",
    location: "",
    rating: 0,
    guests: 0,
    bedrooms: 0,
    beds: 0,
    baths: 0,
    title: "",
    subtitle: "",
    price: 0,
    reviews: 0,
    description: ``,
    wifi: true,
    tv: true,
    washer: true,
    ac: true,
    heating: true,
    breakfast: true,
    freeParking: true,
    refrigerator: true,
    freezer: true,
    dishwasher: true,
    stove: true,
    oven: true,
    coffeeMaker: true,
    url: "",
  },
];

export default data;
